config/routes.rb
Rails.application.routes.draw do
  
  # resources generates all the routes for CRUD in just one line
  # try rake routes in the terminal to see
  resources :posts

  get 'users/sign_in', as: "user_sign_in"
  post 'users/create_session', as: "user_create_session"
  delete 'users/sign_out', as: "user_sign_out"


  get 'users/index'
  get 'users/new'
  get 'users/:id' => "users#show"
  delete 'users/:id' => "users#destroy", as: "user_destroy"
  get 'users/:id/edit' => "users#edit", as: "user_edit"
  patch 'users/:id/update' => "users#update", as: "user"

  # name given to access route by name_path
  # by giving a name to the route, we can just change the route (not the name) in routes.rb instead of changing the route in every file where it is used
  post '/users/create', as: 'users'


  # get "hello_world" => "application#hello_world"


  # different ways of creating a route and mapping it to a controller
  get "application/hello_world"
   get "abc" => "application#hello_world"  


   root "users#index"
  
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def hello_world
  	# render html: "<html><head><title>Title Works</title></head><body>Hello World</body></html>".html_safe
  	@name = "Arjun"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # before_action :set_user, only: [:show, :edit, :update]
  before_action :set_current_user
  before_action :user_signed_in?, only: [:create, :edit, :new]


  # lists all the users
  def index
  	@all_users = User.all
  end

  # renders the page to create a new user
  def new
  	@user = User.new
  end


  # takes data from the form on new.html.erb and creates a new user --> redirects to index
  def create
  	# puts('********')
  	# puts(params)
  	
  	User.create(user_params)

  	redirect_to action: 'index'
  end

  def show
    user_id = params[:id]
    @user = User.find(user_id)
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])

    @user.update(user_params)
    redirect_to action: 'index'
  end


  # ********************ASSIGNMENT 
  # create delete functionality from CRUD
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to action: 'index'
  end

  # sample for creating a done/undone method for a todo app
  # def toggle_status
  #   @task.done=!@task.done
  #   @task.save
  #   re
  # end


  # action to render sign_in page
  def sign_in

  end

  # method to verify the login credentials of a user and add the id to cookies
  def create_session
    # byebug
    user = User.find_by(
        email: params[:email],
        password: params[:password]
      )

    if (user.nil?)
      redirect_to action: "sign_in"
    else
      session[:user_id] = user.id

      redirect_to "/users/#{user.id}"
    end

  end

  # delete the signed in user from cookies
  def sign_out
    if @current_user
      session.delete(:user_id)
      redirect_to action: "index"
    end
  end



  private

  def set_current_user
    byebug
    @current_user = User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    if @current_user.blank?
      redirect_to action: "sign_in"
    end

  end


  def user_params
    params.require(:user).permit(:name, :age, :email, :password)
  end


  # set @user before calling certain actions
  # def set_user
  #   @user = User.find(params[:id])
  # end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/hello_world.html.erb
<h1>Hello World Called </h1>

<%= @name %>

<% x = 5 %>
<% if x > 5 %>
<h5>Greater than 5</h5>
<% else %>
<h4>HEader</h4>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basicproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- <h1>Layout Call Started</h1> -->

	<header>
		<div>
			<p>My Logo</p>
		</div>
		<nav>
			<% if @current_user %>
			<p><%= @current_user.name %></p>
			<p><%= link_to "Sign Out", user_sign_out_path, method: :delete %></p>
			<%else%>
			<%= link_to "Sign in", user_sign_in_path %>
			<% end %>
		</nav>
	</header>
<%= yield %>
	<!-- <h1>Layout Call Ended</h1> -->
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<p>Form From Partial</p>

<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :age %>
	<%= f.number_field :age %>
	<br>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<br>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<br>
	<%= f.submit %>


<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render "form" %>

app/views/users/index.html.erb
<main>

	<% @all_users.each do |u| %>
	<p><%= u.name %></p>
	<p><%= u.age %></p>

	<!-- <a href="/users/<%= u.id %>/edit">Edit</a> -->
	<%= link_to "Edit", user_edit_path(u.id)%>
	<!-- link_to replaces <a> tag with the benefit of using the name of the route  -->



	<a href="/users/<%= u.id %>/">Show Details</a>
	<%= link_to "Delete", user_destroy_path(u.id), method: :delete%>
	<hr>
	<% end %>
</main>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render "form" %>

app/views/users/show.html.erb
<!-- This is the show user page -->
<h1>
	<%= @user.name %>
	<%= @user.age %>

	<!-- We can optimize this by using link_to tag with the name of the route -->
	<!-- <a href="/users/index">All Users</a> -->
	<%= link_to "All Users", users_index_path %>
</h1>

app/views/users/sign_in.html.erb
<main id="sign-in-page">
<h1>User Sign In</h1>

<%= form_tag user_create_session_path do %>
	<%= label_tag :email %>
	<%= email_field_tag :email %>
	<br>

	<%= label_tag :password %>
	<%= password_field_tag :password %>

	<br>
	<%= submit_tag "Sign In" %>

<% end %>
</main>